# Generated by Django 5.0 on 2024-04-20 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('picture', models.ImageField(upload_to='products/')),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('is_sale', models.BooleanField(default=False)),
                ('is_rent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('image1', models.FileField(upload_to='session/')),
                ('image2', models.FileField(upload_to='session/')),
                ('session_type', models.CharField(choices=[('hour', 'Hourly'), ('month', 'Monthly')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_sessions', models.PositiveIntegerField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.session')),
            ],
        ),
        migrations.CreateModel(
            name='HourlySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.session')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_session', models.BooleanField(default=False)),
                ('is_url', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('button_name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, null=True, upload_to='banner/')),
                ('banner_text1', models.CharField(max_length=200)),
                ('banner_text2', models.CharField(max_length=200)),
                ('banner_text3', models.CharField(max_length=200)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_admissions', models.PositiveBigIntegerField()),
                ('session_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.sessiondate')),
            ],
        ),
    ]
