# Generated by Django 5.0.3 on 2024-04-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionscheduling',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='sessionscheduling',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
