# Generated by Django 5.0 on 2024-04-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_product1_session_membershipsession_hourlysession_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
