# Generated by Django 5.0 on 2024-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_session_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='session/'),
        ),
        migrations.AlterField(
            model_name='session',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='session/'),
        ),
    ]
