# Generated by Django 5.0 on 2024-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_session_image1_alter_session_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipsession',
            name='total_sessions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
