# Generated by Django 5.0.3 on 2024-04-05 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_email_verification_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=64, null=True)),
                ("mall", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("currency", models.CharField(max_length=25)),
                ("address", models.TextField()),
                ("license_number", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_employee", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "business_profile",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=100, unique=True)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=255)),
                ("nationality", models.CharField(max_length=100)),
                ("Gender", models.CharField(max_length=5)),
                ("mobile_no", models.CharField(blank=True, max_length=20, null=True)),
                ("passport_no", models.CharField(max_length=20, unique=True)),
                ("passport_expiration_date", models.DateField()),
                ("emirates_id", models.CharField(max_length=20, unique=True)),
                ("id_expiration_date", models.DateField()),
                ("basic_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "house_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "transportation_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("joining_date", models.DateField()),
                (
                    "business_profile",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.businessprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.role",
                    ),
                ),
            ],
        ),
    ]
