# Generated by Django 5.0.3 on 2024-04-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_businessprofile_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="license_number",
        ),
        migrations.RemoveField(
            model_name="businessprofile",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="basic_pay",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="commission_percentage",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emirates_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="house_allowance",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="id_expiration_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="joining_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="passport_expiration_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="passport_no",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="transportation_allowance",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_employee",
        ),
    ]
