# Generated by Django 4.1.13 on 2024-04-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_session_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
