# Generated by Django 5.0.3 on 2024-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_remove_businessprofile_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="Gender",
            new_name="gender",
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
