# Generated by Django 4.1.13 on 2024-04-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_session_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionCategory',
        ),
        migrations.DeleteModel(
            name='Product1',
        ),
        migrations.RemoveField(
            model_name='skate',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='skatebooking',
            name='product',
        ),
        migrations.RemoveField(
            model_name='skatebooking',
            name='session',
        ),
        migrations.RemoveField(
            model_name='skatebooking',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tax',
            new_name='vat',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_rent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SessionScheduling',
        ),
        migrations.DeleteModel(
            name='SessionType',
        ),
        migrations.DeleteModel(
            name='Skate',
        ),
        migrations.DeleteModel(
            name='SkateBooking',
        ),
    ]
