# Generated by Django 5.0.3 on 2024-04-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_rename_gender_employee_gender_employee_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="mobile_no",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="username",
        ),
    ]
