# Generated by Django 5.0.3 on 2024-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "account",
            "0009_remove_employee_first_name_remove_employee_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="is_employee",
        ),
        migrations.AddField(
            model_name="user",
            name="is_employee",
            field=models.BooleanField(default=False),
        ),
    ]
