# Generated by Django 5.0.3 on 2024-04-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_role_is_employee_user_is_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('picture', models.ImageField(upload_to='products/')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(choices=[('UAE', 'United Arab Emirates'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('IN', 'India')], max_length=100),
        ),
    ]
